name: PCF Soluções
favicon: null
layout_spectrum: 0.80454
typography_spectrum: 0.42447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced9ec'
    - '#0b1016'
    - '#fafafa'
    - '#4e4d52'
    - '#7d8b94'
  brandStrength: 0.2964587265159935
  lightness: 0.995848769089207
  saturation: 0.9748925918247551
  rhythmicContrast: 0.4330805176869035
purpose: []
